project:
  type: website

website:
  title: "DAB402003"
  navbar:
    background: primary
    left:
      - href: index.qmd
        text: Home

format:
  html:
    theme: lux
    css: styles.css
    toc: true



